#!/usr/bin/env php
<?php


use Slim\Container;
use Symfony\Component\Console\Application;


require __DIR__ . '/vendor/autoload.php';
$settings = require __DIR__ . '/src/config.php';
$container = new Container($settings);
require __DIR__ . '/src/dependencies.php';
require __DIR__ . '/src/lus_dependencies.php';


$application = new Application();

$application->add($container->get('InstancesList'));
$application->add($container->get('InstancesRemove'));
$application->add($container->get('InstancesSync'));

$application->run();

